spring.application.name=cart-system
server.port=8081

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cart_system}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.connect-timeout=2s
spring.data.redis.timeout=2s

security.jwt.secret=${JWT_SECRET}
security.jwt.ttl=${JWT_TTL:PT15M}